### PR TITLE
flake: add new build dependencies

### LINKED ISSUE #74: [BUG] Failed to build with Nix
**Issue**

Using `nix build` results in a failure due to the following missing dependencies in flake.nix.

- glib
- pango
- gtk3

**Build Log**

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/5026h6k2jmzbh4kzhcphjdxvqa18f139-razer_control_gui
source root is razer_control_gui
Executing cargoSetupPostUnpackHook
Finished cargoSetupPostUnpackHook
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
Executing cargoSetupPostPatchHook
Validating consistency between /build/razer_control_gui/Cargo.lock and /build/cargo-vendor-dir/Cargo.lock
Finished cargoSetupPostPatchHook
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Executing cargoBuildHook
++ env CC_x86_64-unknown-linux-gnu=/nix/store/18bs92p6yf6w2wwxhbplgx02y6anq092-gcc-wrapper-12.3.0/bin/cc CXX_x86_6>
   Compiling proc-macro2 v1.0.66
   Compiling unicode-ident v1.0.11
   Compiling serde v1.0.188
   Compiling pkg-config v0.3.27
   Compiling hashbrown v0.14.5
   Compiling equivalent v1.0.1
   Compiling winnow v0.5.40
   Compiling target-lexicon v0.12.14
   Compiling smallvec v1.13.2
   Compiling heck v0.5.0
   Compiling version-compare v0.2.0
   Compiling libc v0.2.147
   Compiling autocfg v1.1.0
   Compiling version_check v0.9.4
   Compiling syn v1.0.109
   Compiling pin-utils v0.1.0
   Compiling futures-core v0.3.30
   Compiling memchr v2.7.2
   Compiling futures-task v0.3.30
   Compiling pin-project-lite v0.2.14
   Compiling thiserror v1.0.55
   Compiling bitflags v2.4.0
   Compiling heck v0.4.1
   Compiling futures-channel v0.3.30
   Compiling once_cell v1.19.0
   Compiling semver v1.0.23
   Compiling gio v0.18.4
   Compiling cfg-if v1.0.0
   Compiling futures-io v0.3.30
   Compiling utf8parse v0.2.1
   Compiling anstyle-query v1.0.2
   Compiling colorchoice v1.0.0
...skipping...
   Compiling gobject-sys v0.18.0
   Compiling gio-sys v0.18.1
   Compiling pango-sys v0.18.0
   Compiling gdk-sys v0.18.0
   Compiling atk-sys v0.18.0
   Compiling gdk-pixbuf-sys v0.18.0
   Compiling cairo-sys-rs v0.18.2
   Compiling glib-sys v0.19.5
   Compiling gtk-sys v0.18.0
   Compiling gobject-sys v0.19.5
   Compiling gio-sys v0.19.5
The following warnings were emitted during compilation:

warning: `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" PKG_CONFIG_PATH="/nix/store/cmx88a7pb119dqgrckilpm9ia6b6v15f-dbus-1.1>

error: failed to run custom build command for `glib-sys v0.19.5`

Caused by:
  process didn't exit successfully: `/build/razer_control_gui/target/release/build/glib-sys-326b529f123fb2d3/build>
  --- stdout
  cargo:rerun-if-env-changed=GLIB_2.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:warning=`PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" PKG_CONFIG_PATH="/nix/store/cmx88a7pb119dqgrckilpm9ia6b6v15f-d>
  error: could not find system library 'glib-2.0' required by the 'glib-sys' crate

  --- stderr
  Package glib-2.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `glib-2.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'glib-2.0' found
  Package glib-2.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `glib-2.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'glib-2.0' found

warning: build failed, waiting for other jobs to finish...
```

### PR DESCRIPTION
**Pull request by mardukpill**
**Summary:**
- Set the formatter for the flake to `nixfmt-rfc-style`.
- Fixed #74 by adding the required build dependencies.
- Added a new `.desktop` entry for the `razer-settings` GUI.

### CODE REVIEW

**Review by JosuGZ — COMMENTED** [review]
You should probably split the refactor and the actual changes so it is easier to review.

I can see that the only changes are adding `glib`, `pango` and `gtk3` to line 24, which looks good to me (although I have never used nix).

**Comment by mardukpill** [comment]
Ok. I've updated the pr.

**Review by JosuGZ — COMMENTED** [review]
I see that you have also added the .desktop entry, the PR looks good to me.

I have two questions:

- Can't the `.desktop` file be copied from the original inside the `.nix` file? Otherwise it will be in two places
- The `ìnstall.sh` avoids copying this file if the system doesn't have this kind of entry. Do you think every distro will support this `.desktop` files?

**Comment by mardukpill** [comment]
I agree that it is a little weird that the .desktop file is basically in two places, but we have to do slightly different things with Nix `.desktop` file as the path of the binary is generated based off the hash of the derivation. 

For your other question, I have only used Nix on NixOS, so I am not quite sure. If Nix was installed on a different distro and used as the package manager to install razer-laptop-control, it will build fine (I think even if `.desktop` file was unused).

**Pull request merged**
